"""Render incident reports as Markdown or standalone HTML."""

from __future__ import annotations

import html
from typing import Any

from . import analyze, data, mapper, store

DISCLAIMER = (
    "This report is an organizational aid generated by va-incident-mapper. It is not legal advice, "
    "does not decide whether a crime occurred, and may be incomplete or out of date. Statute summaries "
    "are paraphrases. Confirm current law and charging decisions with a licensed Virginia attorney, "
    "the Commonwealth's Attorney, or law enforcement."
)

STRENGTH_LABEL = {
    "primary": "Primary fit",
    "possible": "Possible fit",
    "contested": "Contested / unsettled",
    "civil": "Civil remedy",
}


def _lang(entry: dict[str, Any]) -> dict[str, Any] | None:
    msgs = entry.get("messages") or []
    if not msgs:
        return None
    rows: dict[str, dict[str, Any]] = {}
    for m in msgs:
        for f in analyze.behaviors(m["text"]):
            row = rows.setdefault(f["id"], {"name": f["name"], "weight": f["weight"], "quotes": [], "note": f["legal_note"]})
            for q in f["quotes"]:
                if q not in row["quotes"]:
                    row["quotes"].append(q)
    a = entry["analysis"]
    return {
        "messages": len(msgs),
        "valence": a["valence_mean"],
        "attention": a["attention"],
        "note": analyze.ATTENTION_NOTE[a["attention"]],
        "rows": sorted(rows.values(), key=lambda r: (-r["weight"], r["name"])),
    }


def _accounts(entries: list[dict[str, Any]]) -> dict[str, list[str]]:
    by: dict[str, list[str]] = {}
    for e in entries:
        for m in e.get("messages", []):
            by.setdefault(m["account"], []).append(m["text"])
    return by


def _summary_rows(entries: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    per = []
    for e in entries:
        per.append({"entry": e, "map": mapper.map_types(e["attack_types"])})
    combined = mapper.map_types(sorted({t for e in entries for t in e["attack_types"]})) if entries else None
    return per, combined


def to_markdown(entries: list[dict[str, Any]], *, title: str = "Incident Report", chain_ok: bool = True) -> str:
    meta = data.statutes_meta()
    out = [f"# {title}", "", f"> {DISCLAIMER}", ""]
    out.append(f"- Incidents: {len(entries)}")
    out.append(f"- Log integrity check: {'passed' if chain_ok else 'FAILED (log was altered)'}")
    out.append(f"- Virginia citations last checked: {meta['va_verified_on']}")
    out.append("")
    per, combined = _summary_rows(entries)
    for item in per:
        e, m = item["entry"], item["map"]
        out += [f"## Incident {e['seq']}: {', '.join(m['attack_names'])}", ""]
        out.append(f"- Record ID: `{e['id']}`")
        out.append(f"- Occurred: {e['occurred_at'] or 'not stated'}")
        out.append(f"- Logged (UTC): {e['logged_at']}")
        if e["platform"]:
            out.append(f"- Platform: {e['platform']}")
        if e["accounts"]:
            out.append(f"- Accounts involved: {', '.join(e['accounts'])}")
        out += ["", "**What happened**", "", e["summary"], ""]
        if e["notes"]:
            out += ["**Notes**", "", e["notes"], ""]
        if e["evidence"]:
            out += ["**Evidence files (SHA-256)**", ""]
            out += [f"- {ev['name']} — `{ev['sha256']}` ({ev['bytes']} bytes)" for ev in e["evidence"]]
            out.append("")
        lang = _lang(e)
        if lang:
            out += ["**Language analysis (keyword-based triage)**", "",
                    f"- Messages analyzed: {lang['messages']}; average sentiment {lang['valence']:+.2f}; attention level: {lang['attention']}",
                    f"- {lang['note']}", ""]
            if lang["rows"]:
                out += ["| Weight | Behavior marker | Matched words | Why it matters |", "|---|---|---|---|"]
                for row in lang["rows"]:
                    out.append(f"| {row['weight']} | {row['name']} | {'; '.join(chr(34) + q + chr(34) for q in row['quotes'])} | {row['note']} |")
                out.append("")
        out += ["**Statutes to review with counsel**", "", "| Fit | Citation | What it covers | Penalty |", "|---|---|---|---|"]
        for s in m["statutes"]:
            flag = "" if s["verified"] else " *"
            out.append(f"| {STRENGTH_LABEL[s['strength']]} | {s['cite']}{flag} | {s['title']} | {s['penalty']} |")
        out += ["", "\\* Federal citation not independently re-checked by this tool.", ""]
        out += ["**Caveats**", ""] + [f"- {c}" for c in m["caveats"]] + [""]
    tr = analyze.trend(entries)
    if len(tr["rows"]) >= 2:
        out += ["## Escalation over time", "", "| Entry | When | Sentiment | Attention | Markers |", "|---|---|---|---|---|"]
        out += [f"| {x['seq']} | {x['when']} | {x['valence']:+.2f} | {x['attention']} | {', '.join(x['behaviors']) or '-'} |" for x in tr["rows"]]
        out += [""] + ([f"- {f}" for f in tr["flags"]] if tr["flags"] else ["- No escalation flags."]) + [""]
    by = _accounts(entries)
    if len(by) >= 2:
        cmp_ = analyze.compare(by)
        out += ["## Account comparison (observation only)", "", f"> {analyze.DISCLAIMER}", ""]
        for acct, v in cmp_["accounts"].items():
            out.append(f"- {acct}: sentiment {v['valence_mean']:+.2f}; markers: {', '.join(v['behaviors']) or 'none'}")
        for p in cmp_["pairs"]:
            if p["shared_behaviors"]:
                out.append(f"- {p['a']} vs {p['b']}: shared markers {', '.join(p['shared_behaviors'])} (overlap {p['overlap']:.0%})")
                for bid, ph in p["identical_phrases"].items():
                    out.append(f"  - identical phrases ({bid}): " + "; ".join(chr(34) + x + chr(34) for x in ph))
        out.append("")
    if combined:
        out += ["## Where to report", ""] + [f"- {r}" for r in combined["report_to"]] + [""]
        out += ["## Evidence still worth gathering", ""] + [f"- {d}" for d in combined["document"]] + [""]
    return "\n".join(out).rstrip() + "\n"


def to_html(entries: list[dict[str, Any]], *, title: str = "Incident Report", chain_ok: bool = True) -> str:
    esc = html.escape
    meta = data.statutes_meta()
    per, combined = _summary_rows(entries)
    parts = [
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>",
        "<meta name='viewport' content='width=device-width,initial-scale=1'>",
        f"<title>{esc(title)}</title>",
        "<style>body{font:16px/1.5 system-ui,sans-serif;max-width:860px;margin:2rem auto;padding:0 1rem;color:#1a1a1a}"
        "table{border-collapse:collapse;width:100%;margin:.5rem 0}th,td{border:1px solid #ccc;padding:.4rem .5rem;text-align:left;vertical-align:top}"
        "th{background:#f3f3f3}code{font-size:.85em;word-break:break-all}.note{background:#fff8e1;border-left:4px solid #f0b400;padding:.6rem .8rem}"
        "@media print{body{margin:0}}</style></head><body>",
        f"<h1>{esc(title)}</h1>",
        f"<p class='note'>{esc(DISCLAIMER)}</p>",
        f"<p>Incidents: {len(entries)}. Log integrity check: <strong>{'passed' if chain_ok else 'FAILED (log was altered)'}</strong>. "
        f"Virginia citations last checked: {esc(meta['va_verified_on'])}.</p>",
    ]
    for item in per:
        e, m = item["entry"], item["map"]
        parts.append(f"<h2>Incident {e['seq']}: {esc(', '.join(m['attack_names']))}</h2><ul>")
        parts.append(f"<li>Record ID: <code>{esc(e['id'])}</code></li>")
        parts.append(f"<li>Occurred: {esc(e['occurred_at'] or 'not stated')}</li><li>Logged (UTC): {esc(e['logged_at'])}</li>")
        if e["platform"]:
            parts.append(f"<li>Platform: {esc(e['platform'])}</li>")
        if e["accounts"]:
            parts.append(f"<li>Accounts involved: {esc(', '.join(e['accounts']))}</li>")
        parts.append(f"</ul><h3>What happened</h3><p>{esc(e['summary'])}</p>")
        if e["notes"]:
            parts.append(f"<h3>Notes</h3><p>{esc(e['notes'])}</p>")
        if e["evidence"]:
            parts.append("<h3>Evidence files (SHA-256)</h3><ul>")
            for ev in e["evidence"]:
                parts.append(f"<li>{esc(ev['name'])} — <code>{esc(ev['sha256'])}</code> ({ev['bytes']} bytes)</li>")
            parts.append("</ul>")
        lang = _lang(e)
        if lang:
            parts.append(f"<h3>Language analysis (keyword-based triage)</h3><p>Messages analyzed: {lang['messages']}; average sentiment {lang['valence']:+.2f}; attention level: <strong>{esc(lang['attention'])}</strong>.<br>{esc(lang['note'])}</p>")
            if lang["rows"]:
                parts.append("<table><tr><th>Weight</th><th>Behavior marker</th><th>Matched words</th><th>Why it matters</th></tr>")
                for row in lang["rows"]:
                    parts.append(f"<tr><td>{row['weight']}</td><td>{esc(row['name'])}</td><td>{esc('; '.join(chr(34) + q + chr(34) for q in row['quotes']))}</td><td>{esc(row['note'])}</td></tr>")
                parts.append("</table>")
        parts.append("<h3>Statutes to review with counsel</h3><table><tr><th>Fit</th><th>Citation</th><th>What it covers</th><th>Penalty</th></tr>")
        for s in m["statutes"]:
            flag = "" if s["verified"] else " *"
            parts.append(
                f"<tr><td>{esc(STRENGTH_LABEL[s['strength']])}</td><td>{esc(s['cite'])}{flag}</td>"
                f"<td>{esc(s['title'])}</td><td>{esc(s['penalty'])}</td></tr>"
            )
        parts.append("</table><p><small>* Federal citation not independently re-checked by this tool.</small></p>")
        parts.append("<h3>Caveats</h3><ul>" + "".join(f"<li>{esc(c)}</li>" for c in m["caveats"]) + "</ul>")
    tr = analyze.trend(entries)
    if len(tr["rows"]) >= 2:
        parts.append("<h2>Escalation over time</h2><table><tr><th>Entry</th><th>When</th><th>Sentiment</th><th>Attention</th><th>Markers</th></tr>")
        for x in tr["rows"]:
            parts.append(f"<tr><td>{x['seq']}</td><td>{esc(x['when'])}</td><td>{x['valence']:+.2f}</td><td>{esc(x['attention'])}</td><td>{esc(', '.join(x['behaviors']) or '-')}</td></tr>")
        parts.append("</table><ul>" + "".join(f"<li>{esc(f)}</li>" for f in (tr["flags"] or ["No escalation flags."])) + "</ul>")
    by = _accounts(entries)
    if len(by) >= 2:
        cmp_ = analyze.compare(by)
        parts.append(f"<h2>Account comparison (observation only)</h2><p class='note'>{esc(analyze.DISCLAIMER)}</p><ul>")
        for acct, v in cmp_["accounts"].items():
            parts.append(f"<li>{esc(acct)}: sentiment {v['valence_mean']:+.2f}; markers: {esc(', '.join(v['behaviors']) or 'none')}</li>")
        for p in cmp_["pairs"]:
            if p["shared_behaviors"]:
                parts.append(f"<li>{esc(p['a'])} vs {esc(p['b'])}: shared markers {esc(', '.join(p['shared_behaviors']))} (overlap {p['overlap']:.0%})")
                for bid, ph in p["identical_phrases"].items():
                    parts.append(f"<br>identical phrases ({esc(bid)}): {esc('; '.join(chr(34) + x + chr(34) for x in ph))}")
                parts.append("</li>")
        parts.append("</ul>")
    if combined:
        parts.append("<h2>Where to report</h2><ul>" + "".join(f"<li>{esc(r)}</li>" for r in combined["report_to"]) + "</ul>")
        parts.append("<h2>Evidence still worth gathering</h2><ul>" + "".join(f"<li>{esc(d)}</li>" for d in combined["document"]) + "</ul>")
    parts.append("</body></html>")
    return "".join(parts)
